### PR TITLE
(Feature) Fix my size light dash

### LINKED ISSUE #405: My size do not display light dash on empty component
“My size” in the order book should display a light dash instead of “0.0000”

### PR DESCRIPTION
**Pull request by Agupane**
Closes #405 

Before:
image
After:
image

### CODE REVIEW

File: src/components/marketplace/order_book.tsx [hunk 1]
```diff
@@ -48,10 +48,13 @@ const orderToRow = (
...
     const mySizeConverted = tokenAmountInUnits(mySize, baseToken.decimals, UI_DECIMALS_DISPLAYED_ORDER_SIZE);
+    const zeroDecimals = '0'.repeat(UI_DECIMALS_DISPLAYED_ORDER_SIZE);
+    const mySizeStrDisplay = '0.'.concat(zeroDecimals);
+    const displayColor = mySizeConverted !== mySizeStrDisplay ? undefined : '#dedede';
     const mySizeRow =
         web3State !== Web3State.Locked && web3State !== Web3State.NotInstalled ? (
-            <CustomTD styles={{ tabular: true, textAlign: 'right' }}>
-                {mySizeConverted !== '0.00' ? mySizeConverted : '-'}
+            <CustomTD styles={{ tabular: true, textAlign: 'right', color: displayColor }}>
+                {mySizeConverted !== mySizeStrDisplay ? mySizeConverted : '-'}
```
Comment (fvictorio) [inline src/components/marketplace/order_book.tsx]: Q: Instead of this, can we do something like `!mySize.eq(new BigNumber(0))`?

Comment (Agupane) [reply src/components/marketplace/order_book.tsx]: Yes, it's a good idea, It's done now

File: src/components/erc20/marketplace/order_book.tsx [hunk 2]
```diff
@@ -48,10 +48,11 @@ const orderToRow = (
     }, new BigNumber(0));
 
     const mySizeConverted = tokenAmountInUnits(mySize, baseToken.decimals, UI_DECIMALS_DISPLAYED_ORDER_SIZE);
+    const displayColor = !mySize.eq(new BigNumber(0)) ? undefined : '#dedede';
```
Comment (fvictorio) [inline src/components/erc20/marketplace/order_book.tsx]: Sorry for being a PITA, but since this expression is used twice and it's not exactly readable, can we extract it to a variable?

```
const isSizeEmpty = mySize.eq(new BigNumber(0))
```

(or whichever name you prefer).

Comment (Agupane) [reply src/components/erc20/marketplace/order_book.tsx]: Sure, no problem, it's done, please check it again

**Review by fvictorio — APPROVED** [review]
